name: C++ CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Use the OS defined in the matrix

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Define the operating systems
        build_type: [Debug, Release]  # Define the build types

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.28.1'

      - name: Install GTest
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libgtest-dev
            cd /usr/src/gtest
            sudo cmake .
            sudo make
            sudo cp *.a /usr/lib
          fi

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
